# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=254)),
                ('nickname', models.CharField(max_length=254)),
                ('accept', models.IntegerField()),
                ('city1', models.CharField(default='默认:北京-北京', max_length=60)),
                ('city2', models.CharField(default='默认:北京-北京', max_length=60)),
                ('city3', models.CharField(default='默认:北京-北京', max_length=60)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
