# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_now',
            fields=[
                ('city', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('weat_now', models.CharField(max_length=40)),
                ('temp_now', models.CharField(max_length=40)),
                ('humi_now', models.CharField(max_length=40)),
                ('airq_now', models.CharField(max_length=40)),
                ('rays_now', models.CharField(max_length=40)),
                ('wind_now', models.CharField(max_length=40)),
                ('time_now', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_tom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tom', models.CharField(max_length=40)),
                ('weat_tom', models.CharField(max_length=40)),
                ('temp_tom', models.CharField(max_length=40)),
                ('airq_tom', models.CharField(max_length=40)),
                ('wind_tom', models.CharField(max_length=40)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Weather_now')),
            ],
        ),
    ]
